import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { SidebarProvider } from './components/SidebarProvider';

const inter = Manrope({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Taskify.ai',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SidebarProvider>
        <body className={inter.className}>{children}</body>
      </SidebarProvider>
    </html>
  );
}
