import type { Metadata } from 'next';
import {
  Poppins,
  Open_Sans,
  Roboto,
  Montserrat,
  Roboto_Condensed,
  Merriweather,
  Nunito,
  Nunito_Sans,
  Lato,
} from 'next/font/google';
import './globals.css';

const inter = Open_Sans({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Taskify.ai',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
